### ISSUE TITLE
This project has no license

### ISSUE THREAD

**Issue by maxhbr** [MangoIV/le_chiff_ble#1]
It might be worth to add one to make it actually (re)usable and Open Source.

**Comment by MangoIV** [comment]
I haven't figured out a license yet, your request is valid but I think that for personal use not having a license it totally fine and for every retailer who actually wants to sell this I want to have personal communication anyway so in general I think it makes the most sense to keep it as is. If I find a license that makes sense for my use case then I'll add it. Also mind that with hardware it's generally a bit more complicated than with software (I'm no lawyer and I don't wanna contact one to figure out a license).

**Comment by MangoIV** [comment]
I might make it gpl v3 to follow the original project although, again, I don't know whether I have to because I remade the whole board from scratch, it just fits the same case. again, I don't know whether this is even possible/necessary with hardware designs.

**Comment by maxhbr** [comment]
> I think that for personal use not having a license it totally fine

sadly that is wrong, without an license no one is actually allowed to use. The default is no-rights.

GPL-3.0 sounds like the right choice, especially if you are building on top of stuff licensed under it. Otherwise https://choosealicense.com/ might be interesting.
